doctrine:
    dbal:
        # configure these for your database server
        driver: '%env(resolve:DB_CONNECTION)%'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        host: '%env(resolve:DB_HOST)%'
        port: '%env(resolve:DB_PORT)%'
        dbname: '%env(resolve:DB_DATABASE)%'
        user: '%env(resolve:DB_USERNAME)%'
        password: '%env(resolve:DB_PASSWORD)%'
        mapping_types:
            bit: boolean
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine'
                prefix: 'App\Entity'
                alias: App
