twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        app_name: '%app.name%'
        app_version: '%app.version%'
        app_style: '@App\Service\Style'
        theme_default: '%theme_default%'

when@test:
    twig:
        strict_variables: true
